### ISSUE TITLE
Keys restore error - Invalid argument(s): Invalid or corrupted pad block

### ISSUE THREAD

**Issue by ricardobrg** [tiki/wallet#10]

**Comment by ricardobrg** [comment]
Steps to reproduce:

1. Install the app
2. Create keys and login
3. Reinstall the app (or clean app data)
4. Restore the keys created

The app loads the key from backup server but during key decryption in TikiKeysModel.decrypt(), it throws this error.

**Comment by mike-audi** [comment]
not a bug. this means the passphrase was wrong
