### ISSUE TITLE
Monitoring of the tiki chain

### ISSUE THREAD

**Issue by mike-audi** [tiki/wallet#33]
Using a combination of sentry and amplitude as developers should be able to determine the volume and performance of the tiki chain spanning from minting to backup. 

Acceptance Criteria:
- Mint rate 
- Backup ratio
- Bug/performance monitoring from start to finish

**Comment by ricardobrg** [comment]
![Image](https://user-images.githubusercontent.com/8357343/175054346-81d9f801-1456-4b81-8198-75cb6e16967e.png)
